export const jobs = [
  // IT Jobs
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop',
    tags: ['Flutter', 'Postgres', 'REST'],
    title: 'Mobile Developer',
    company: 'Tech Corp',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,500 - $2,500',
    jobType: 'Full-time',
    experience: '2+ years',
    description: 'We are looking for an experienced Mobile Developer to join our dynamic team. You will work on building innovative mobile applications using Flutter for both iOS and Android platforms.',
    responsibilities: ['Develop and maintain mobile applications using Flutter', 'Collaborate with backend teams on REST API integration', 'Optimize database queries using PostgreSQL', 'Write clean, maintainable code', 'Participate in code reviews', 'Debug and optimize mobile application performance', 'Work with UI/UX designers to implement beautiful interfaces'],
    requirements: ['Strong knowledge of Flutter framework and Dart programming', 'Experience with PostgreSQL database design', 'Understanding of REST APIs and HTTP protocols', 'Good communication and teamwork skills', 'Problem-solving abilities and critical thinking', 'Experience with version control (Git)', 'Knowledge of mobile app deployment processes'],
    benefits: ['Competitive salary and performance bonuses', 'Comprehensive health insurance', 'Flexible working hours', 'Professional development and training budget', 'Free snacks, coffee, and beverages', 'Collaborative and innovative work environment', 'Career growth opportunities'],
    aboutCompany: 'Tech Corp is a leading software development company specializing in mobile and web applications.',
    postedDate: '2025-10-01',
    applicants: 24,
    views: 512
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    tags: ['Software', 'IT'],
    title: 'Software Engineer',
    company: 'Digital Solutions',
    location: 'Remote',
    category: 'IT',
    salary: '$2,000 - $3,500',
    jobType: 'Full-time',
    experience: '3+ years',
    description: 'Digital Solutions is seeking a talented Software Engineer to help build scalable software solutions for international clients. You will work on challenging projects that impact millions of users.',
    responsibilities: ['Design and implement scalable software solutions', 'Write efficient and maintainable code following best practices', 'Debug and optimize applications for performance', 'Work with cross-functional teams including designers and product managers', 'Document technical specifications and system architecture', 'Participate in system design discussions and technical planning', 'Mentor junior developers and code review contributions'],
    requirements: ["Bachelor's degree in Computer Science or equivalent experience", 'Strong programming skills in multiple languages', 'Experience with software development lifecycle (SDLC)', 'Knowledge of design patterns and architecture', 'Excellent problem-solving and analytical skills', 'Understanding of databases and data structures', 'Experience with cloud platforms (AWS, Azure, or GCP)'],
    benefits: ['Remote work with flexible location', 'Highly competitive compensation package', 'Unlimited learning and development opportunities', 'Flexible working hours and schedule', 'Team performance bonuses and stock options', 'Home office setup allowance', 'Annual international conference attendance'],
    aboutCompany: 'Digital Solutions is a pioneer in enterprise software solutions serving Fortune 500 companies globally.',
    postedDate: '2025-09-28',
    applicants: 47,
    views: 892
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
    tags: ['JSON', 'API'],
    title: 'Backend Developer',
    company: 'StartUp Inc',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,800 - $2,800',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'StartUp Inc is looking for a Backend Developer to build robust server-side applications and RESTful APIs. Join a fast-growing startup with great opportunities for growth.',
    responsibilities: ['Develop backend services and RESTful APIs using modern frameworks', 'Work with JSON data structures and data serialization', 'Implement database solutions and optimize queries', 'Ensure application security and data protection', 'Perform performance optimization and load testing', 'Write automated tests and implement CI/CD pipelines', 'Collaborate with frontend developers on API specifications'],
    requirements: ['Experience with backend frameworks (Node.js, Python, Java)', 'Strong JSON and API design knowledge', 'Database design and SQL expertise', 'Version control experience (Git)', 'Linux/Unix command line basics', 'Understanding of REST principles and HTTP', 'Experience with Docker and containerization'],
    benefits: ['Startup equity and stock options', 'Fast-track growth opportunities', 'Flexible working hours', 'Mentorship from senior developers', 'Career development and training', 'Modern tech stack', 'Collaborative startup culture'],
    aboutCompany: 'StartUp Inc is a rapidly growing tech startup focused on building innovative SaaS solutions for Southeast Asia.',
    postedDate: '2025-10-05',
    applicants: 32,
    views: 645
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=300&fit=crop',
    tags: ['Postgres', 'MongoDB'],
    title: 'Database Admin',
    company: 'Data Systems',
    location: 'Siem Reap',
    category: 'IT',
    salary: '$1,600 - $2,400',
    jobType: 'Full-time',
    experience: '3+ years',
    description: 'Data Systems is seeking a Database Administrator to manage and maintain our critical database infrastructure supporting thousands of users.',
    responsibilities: ['Manage PostgreSQL and MongoDB database servers', 'Perform regular backups and disaster recovery procedures', 'Monitor database performance and resource usage', 'Optimize queries and database schema', 'Handle database security and access controls', 'Troubleshoot and resolve database issues', 'Document database procedures and best practices'],
    requirements: ['Expert-level PostgreSQL and MongoDB knowledge', 'Database design and normalization experience', 'Backup and recovery procedure expertise', 'Performance tuning and optimization skills', 'Database security and authentication knowledge', 'Linux/Unix system administration basics', 'Experience with database replication and clustering'],
    benefits: ['Stable, secure employment', 'Comprehensive health benefits', 'Overtime compensation', 'Professional training and certifications', 'Supportive team environment', 'Career stability and growth', 'On-call compensation'],
    aboutCompany: 'Data Systems is a leading data infrastructure company providing database solutions to enterprise clients.',
    postedDate: '2025-10-02',
    applicants: 18,
    views: 389
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop',
    tags: ['React', 'UI/UX'],
    title: 'Frontend Developer',
    company: 'Creative Agency',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,700 - $2,700',
    jobType: 'Full-time',
    experience: '2+ years',
    description: 'Creative Agency seeks a Frontend Developer to build beautiful and responsive user interfaces for web and mobile applications.',
    responsibilities: ['Build responsive web interfaces using React and modern JavaScript', 'Implement React components with state management', 'Optimize frontend performance and load times', 'Collaborate closely with UI/UX designers', 'Ensure cross-browser and cross-device compatibility', 'Write unit tests and implement testing strategies', 'Implement SEO best practices and accessibility standards'],
    requirements: ['Expert-level React.js knowledge', 'Strong HTML, CSS, and JavaScript proficiency', 'Understanding of UI/UX principles and design systems', 'Responsive design and mobile-first development', 'Browser developer tools proficiency', 'Version control (Git) experience', 'Experience with REST API integration'],
    benefits: ['Creative and collaborative environment', 'Portfolio-building opportunities', 'Latest design and development tools', 'Excellent work-life balance', 'Performance bonuses', 'Creative freedom and autonomy', 'Team outings and social events'],
    aboutCompany: 'Creative Agency is a digital creative studio known for award-winning web and mobile interfaces.',
    postedDate: '2025-10-04',
    applicants: 56,
    views: 1203
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=300&fit=crop',
    tags: ['DevOps', 'AWS'],
    title: 'Cloud Engineer',
    company: 'Cloud Services',
    location: 'Remote',
    category: 'IT',
    salary: '$2,200 - $3,200',
    jobType: 'Full-time',
    experience: '3-5 years',
    description: 'Cloud Services is hiring a Cloud Engineer to design and maintain cloud infrastructure supporting enterprise clients worldwide.',
    responsibilities: ['Design cloud architecture and infrastructure', 'Manage AWS services and cloud resources', 'Implement DevOps practices and automation', 'Monitor system performance and availability', 'Ensure high availability and disaster recovery', 'Implement security best practices', 'Optimize cloud costs and resource utilization'],
    requirements: ['AWS certification preferred', 'DevOps experience and best practices', 'Infrastructure as Code (Terraform, CloudFormation)', 'Linux administration skills', 'CI/CD pipelines and automation', 'Networking and security knowledge', 'Container orchestration (Kubernetes) experience'],
    benefits: ['Remote flexibility and autonomy', 'Highly competitive salary', 'AWS certification covered', 'Continuous learning opportunities', 'Stock options and equity', 'Home office setup budget', 'Relocation assistance if needed'],
    aboutCompany: 'Cloud Services is a premier cloud infrastructure provider serving enterprise clients across Asia-Pacific.',
    postedDate: '2025-09-29',
    applicants: 38,
    views: 756
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=300&fit=crop',
    tags: ['Python', 'Django'],
    title: 'Full Stack Developer',
    company: 'Web Solutions',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,900 - $2,900',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'Web Solutions is looking for a Full Stack Developer to build complete web applications from frontend to backend using Python and Django.',
    responsibilities: ['Develop full-stack web applications using Python and Django', 'Design and implement database schemas', 'Build responsive frontend interfaces', 'Implement backend APIs and business logic', 'Deploy applications to production servers', 'Maintain and optimize existing applications', 'Collaborate with product team on feature development'],
    requirements: ['Strong Python and Django framework knowledge', 'Frontend development skills (HTML, CSS, JavaScript)', 'Database design and SQL expertise', 'REST API development experience', 'Version control and Git proficiency', 'Understanding of web security principles', 'Deployment and DevOps basics'],
    benefits: ['Competitive salary and bonuses', 'Professional development budget', 'Flexible working arrangement', 'Collaborative team environment', 'Health and wellness programs', 'Learning allowance for courses', 'Project diversity and challenges'],
    aboutCompany: 'Web Solutions is a web development company specializing in custom web applications for businesses.',
    postedDate: '2025-10-03',
    applicants: 41,
    views: 834
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop',
    tags: ['Java', 'Spring'],
    title: 'Java Developer',
    company: 'Enterprise Corp',
    location: 'Remote',
    category: 'IT',
    salary: '$2,100 - $3,300',
    jobType: 'Full-time',
    experience: '3-5 years',
    description: 'Enterprise Corp is seeking an experienced Java Developer to build robust enterprise applications using Spring framework.',
    responsibilities: ['Develop enterprise Java applications using Spring Boot and Spring Cloud', 'Design and implement microservices architecture', 'Work with relational and NoSQL databases', 'Implement security and authentication mechanisms', 'Write unit and integration tests', 'Participate in code reviews and design discussions', 'Troubleshoot and resolve production issues'],
    requirements: ['Expert-level Java programming skills', 'Spring Framework and Spring Boot expertise', 'Microservices architecture knowledge', 'SQL and NoSQL database experience', 'Testing frameworks and practices', 'Maven/Gradle build tools', 'Understanding of enterprise design patterns'],
    benefits: ['Premium salary package', 'Remote work flexibility', 'Professional certifications covered', 'Unlimited learning resources', 'Performance-based bonuses', 'Stock options', 'Comprehensive health coverage'],
    aboutCompany: 'Enterprise Corp develops mission-critical enterprise software for large corporations.',
    postedDate: '2025-09-27',
    applicants: 52,
    views: 1045
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
    tags: ['JavaScript', 'Node.js'],
    title: 'Node.js Developer',
    company: 'StartUp Hub',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,600 - $2,600',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'StartUp Hub is looking for a Node.js Developer to build scalable backend services for our growing platform.',
    responsibilities: ['Develop backend services using Node.js and Express', 'Build RESTful APIs and GraphQL servers', 'Implement database operations and queries', 'Handle asynchronous programming and promises', 'Implement authentication and authorization', 'Optimize application performance', 'Write comprehensive test cases'],
    requirements: ['Strong Node.js and JavaScript expertise', 'Express.js framework knowledge', 'RESTful API design principles', 'Database experience (MySQL, MongoDB)', 'Asynchronous programming patterns', 'NPM package ecosystem knowledge', 'Understanding of web security'],
    benefits: ['Startup growth opportunities', 'Competitive compensation', 'Flexible schedule', 'Learning and development', 'Team collaboration', 'Modern technology stack', 'Career advancement'],
    aboutCompany: 'StartUp Hub is a fast-growing startup building innovative backend solutions.',
    postedDate: '2025-10-01',
    applicants: 29,
    views: 612
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
    tags: ['DevOps', 'Docker'],
    title: 'DevOps Engineer',
    company: 'Tech Infrastructure',
    location: 'Remote',
    category: 'IT',
    salary: '$2,000 - $3,000',
    jobType: 'Full-time',
    experience: '3+ years',
    description: 'Tech Infrastructure is seeking a DevOps Engineer to manage infrastructure, deployment pipelines, and containerized applications.',
    responsibilities: ['Manage Docker containers and Kubernetes orchestration', 'Set up and maintain CI/CD pipelines', 'Monitor system infrastructure and performance', 'Implement infrastructure automation', 'Manage cloud resources and scaling', 'Implement logging and monitoring solutions', 'Handle incident response and troubleshooting'],
    requirements: ['Docker and Kubernetes expertise', 'CI/CD tools (Jenkins, GitLab CI, GitHub Actions)', 'Infrastructure as Code (Terraform)', 'Linux system administration', 'Cloud platform experience (AWS, GCP)', 'Scripting and automation skills', 'Monitoring and logging tools'],
    benefits: ['Remote flexibility', 'Competitive salary', 'On-call support compensation', 'Professional development', 'Technology certifications', 'Stock options', 'Flexible time off'],
    aboutCompany: 'Tech Infrastructure provides infrastructure solutions to tech companies across Asia.',
    postedDate: '2025-10-02',
    applicants: 25,
    views: 523
  },
  {
    id: 11,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=300&fit=crop',
    tags: ['PHP', 'Laravel'],
    title: 'Laravel Developer',
    company: 'Web Agency',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,400 - $2,400',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'Web Agency is looking for a Laravel Developer to build web applications for various clients using Laravel framework.',
    responsibilities: ['Develop web applications using Laravel framework', 'Design database schemas and relationships', 'Build RESTful APIs and web services', 'Implement authentication and authorization', 'Optimize application performance', 'Work with frontend teams on integration', 'Maintain and update existing applications'],
    requirements: ['Strong Laravel and PHP knowledge', 'MySQL and database design expertise', 'RESTful API development', 'Blade templating engine', 'Composer and Laravel packages', 'Version control with Git', 'Understanding of MVC architecture'],
    benefits: ['Competitive salary', 'Project diversity', 'Flexible working hours', 'Team support and mentoring', 'Professional growth', 'Health insurance', 'Performance bonuses'],
    aboutCompany: 'Web Agency specializes in custom web application development for diverse clients.',
    postedDate: '2025-10-04',
    applicants: 33,
    views: 678
  },
  {
    id: 12,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop',
    tags: ['Data Science', 'ML'],
    title: 'Data Scientist',
    company: 'AI Labs',
    location: 'Remote',
    category: 'IT',
    salary: '$2,500 - $3,800',
    jobType: 'Full-time',
    experience: '3-5 years',
    description: 'AI Labs is seeking a Data Scientist to develop machine learning models and analyze complex datasets for AI solutions.',
    responsibilities: ['Develop and train machine learning models', 'Perform data analysis and statistical modeling', 'Clean and preprocess large datasets', 'Implement feature engineering techniques', 'Evaluate model performance and optimize', 'Deploy models to production', 'Collaborate with engineering teams on integration'],
    requirements: ['Python or R programming expertise', 'Machine learning frameworks (TensorFlow, scikit-learn)', 'Statistical analysis and mathematics knowledge', 'Data visualization skills', 'SQL and database querying', 'Understanding of deep learning concepts', 'Experience with big data tools'],
    benefits: ['Premium salary package', 'Remote work flexibility', 'Research opportunities', 'Conference attendance', 'GPU computing resources', 'Flexible schedule', 'Stock options'],
    aboutCompany: 'AI Labs is an artificial intelligence research company developing cutting-edge ML solutions.',
    postedDate: '2025-09-26',
    applicants: 44,
    views: 1124
  },
  {
    id: 13,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=300&fit=crop',
    tags: ['QA', 'Testing'],
    title: 'QA Engineer',
    company: 'Quality Assurance',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,200 - $1,800',
    jobType: 'Full-time',
    experience: '2-3 years',
    description: 'Quality Assurance is looking for a QA Engineer to ensure software quality through comprehensive testing and automation.',
    responsibilities: ['Design and execute test cases and test plans', 'Perform manual and automated testing', 'Write test automation scripts using Selenium', 'Report and track bugs and issues', 'Collaborate with developers on bug fixes', 'Perform regression and performance testing', 'Document testing procedures and results'],
    requirements: ['QA and testing methodologies knowledge', 'Test automation frameworks (Selenium, Appium)', 'Manual and automated testing skills', 'Bug tracking tools experience', 'Basic programming or scripting skills', 'Understanding of SDLC', 'Attention to detail and reporting skills'],
    benefits: ['Competitive salary', 'Health insurance', 'Career development', 'Supportive environment', 'Testing tools training', 'Performance bonuses', 'Work-life balance'],
    aboutCompany: 'Quality Assurance is a dedicated QA services provider ensuring software excellence.',
    postedDate: '2025-10-05',
    applicants: 20,
    views: 445
  },
  {
    id: 14,
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400&h=300&fit=crop',
    tags: ['Kubernetes', 'CI/CD'],
    title: 'Site Reliability Engineer',
    company: 'Cloud Operations',
    location: 'Remote',
    category: 'IT',
    salary: '$2,300 - $3,500',
    jobType: 'Full-time',
    experience: '4-6 years',
    description: 'Cloud Operations is seeking a Site Reliability Engineer to maintain and improve system reliability and performance at scale.',
    responsibilities: ['Manage and optimize Kubernetes clusters', 'Implement and maintain CI/CD pipelines', 'Monitor system reliability and availability', 'Implement infrastructure automation', 'Respond to and resolve incidents', 'Implement observability and monitoring', 'Collaborate on infrastructure improvements'],
    requirements: ['Kubernetes and container orchestration', 'CI/CD tools and practices', 'Infrastructure as Code expertise', 'System administration and Linux', 'Monitoring and alerting tools', 'On-call incident management', 'Scripting and automation languages'],
    benefits: ['Premium compensation', 'Remote flexibility', 'On-call rotation pay', 'Professional development', 'Certifications covered', 'Stock options', 'Unlimited PTO'],
    aboutCompany: 'Cloud Operations manages critical infrastructure for enterprise SaaS platforms.',
    postedDate: '2025-09-25',
    applicants: 35,
    views: 789
  },
  {
    id: 15,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop',
    tags: ['API', 'REST'],
    title: 'API Developer',
    company: 'Integration Solutions',
    location: 'Phnom Penh',
    category: 'IT',
    salary: '$1,700 - $2,700',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'Integration Solutions is looking for an API Developer to design and build RESTful APIs for various integrations and services.',
    responsibilities: ['Design and build RESTful APIs', 'Implement API authentication and security', 'Design database schemas for APIs', 'Write API documentation', 'Implement rate limiting and caching', 'Perform API testing and validation', 'Support API integrations for clients'],
    requirements: ['RESTful API design principles', 'Backend framework experience', 'API security best practices', 'Database design', 'API documentation tools', 'Version control and Git', 'Understanding of HTTP and protocols'],
    benefits: ['Competitive salary', 'API development focus', 'Learning opportunities', 'Flexible schedule', 'Team collaboration', 'Health insurance', 'Performance incentives'],
    aboutCompany: 'Integration Solutions specializes in building robust API solutions for businesses.',
    postedDate: '2025-10-01',
    applicants: 27,
    views: 534
  },
  // Marketing Jobs
  {
    id: 16,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    tags: ['Digital', 'SEO'],
    title: 'Digital Marketing Manager',
    company: 'Marketing Pro',
    location: 'Phnom Penh',
    category: 'Marketing',
    salary: '$1,200 - $2,000',
    jobType: 'Full-time',
    experience: '3+ years',
    description: 'Marketing Pro is looking for a Digital Marketing Manager to lead our online marketing campaigns and drive customer acquisition.',
    responsibilities: ['Plan and execute comprehensive digital marketing strategies', 'Manage SEO and SEM campaigns and budgets', 'Analyze marketing metrics and create detailed reports', 'Lead and mentor marketing team members', 'Create engaging marketing content and campaigns', 'Manage social media advertising and paid campaigns', 'Collaborate with sales team on lead generation'],
    requirements: ['Digital marketing expertise and proven track record', 'SEO/SEM and PPC knowledge', 'Analytics tools proficiency (Google Analytics, SEMrush)', 'Leadership and team management skills', 'Content marketing experience', 'Data analysis and reporting skills', 'Knowledge of marketing automation tools'],
    benefits: ['Competitive salary with performance bonuses', 'Marketing campaign budget', 'Team leadership opportunities', 'Clear career growth path', 'Flexible working hours', 'Professional development budget', 'Results-based incentives'],
    aboutCompany: 'Marketing Pro is a premier digital marketing agency specializing in B2C and B2B marketing.',
    postedDate: '2025-09-30',
    applicants: 29,
    views: 734
  },
  {
    id: 17,
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=400&h=300&fit=crop',
    tags: ['Social Media', 'Content'],
    title: 'Social Media Manager',
    company: 'Brand Agency',
    location: 'Remote',
    category: 'Marketing',
    salary: '$1,000 - $1,800',
    jobType: 'Full-time',
    experience: '2+ years',
    description: 'Brand Agency seeks a Social Media Manager to manage our social media presence and engage with our growing community.',
    responsibilities: ['Create and schedule social media content', 'Engage with followers and manage community', 'Monitor social media trends and insights', 'Manage social media advertising campaigns', 'Analyze social media metrics and ROI', 'Collaborate with marketing team on campaigns', 'Create monthly social media reports'],
    requirements: ['Social media platform expertise (Facebook, Instagram, TikTok, LinkedIn)', 'Content creation and copywriting skills', 'Community management and engagement', 'Social media analytics knowledge', 'Creative thinking and visual content skills', 'Basic graphic design skills', 'Understanding of social media algorithms'],
    benefits: ['Remote work opportunity', 'Creative freedom', 'Flexible schedule', 'Content creation tools access', 'Community building focus', 'Performance bonuses', 'Professional development'],
    aboutCompany: 'Brand Agency specializes in social media management and content creation for brands.',
    postedDate: '2025-10-03',
    applicants: 38,
    views: 876
  },
  {
    id: 18,
    image: 'https://images.unsplash.com/photo-1455849318169-8d3cb32ba205?w=400&h=300&fit=crop',
    tags: ['Content', 'Writing'],
    title: 'Content Creator',
    company: 'Media House',
    location: 'Phnom Penh',
    category: 'Marketing',
    salary: '$900 - $1,600',
    jobType: 'Full-time',
    experience: '1-3 years',
    description: 'Media House is looking for a Content Creator to produce engaging content across multiple platforms and formats.',
    responsibilities: ['Write engaging blog posts and articles', 'Create multimedia content (videos, infographics)', 'Research topics and industry trends', 'Edit and proofread content for quality', 'Collaborate with marketing and design teams', 'Manage content calendar and deadlines', 'Optimize content for SEO'],
    requirements: ['Strong writing and storytelling skills', 'Content creation experience across platforms', 'Research and fact-checking abilities', 'Multimedia content creation skills', 'SEO optimization knowledge', 'Time management and organizational skills', 'Understanding of target audiences'],
    benefits: ['Creative environment', 'Portfolio building opportunities', 'Learning resources', 'Flexible deadlines', 'Team collaborations', 'Professional development', 'Performance incentives'],
    aboutCompany: 'Media House produces quality content for diverse audiences and platforms.',
    postedDate: '2025-10-02',
    applicants: 42,
    views: 912
  },
  {
    id: 19,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    tags: ['Analytics', 'Data'],
    title: 'Marketing Analyst',
    company: 'Data Insights',
    location: 'Remote',
    category: 'Marketing',
    salary: '$1,100 - $1,900',
    jobType: 'Full-time',
    experience: '2-4 years',
    description: 'Data Insights seeks a Marketing Analyst to analyze marketing data and optimize campaigns for better ROI.',
    responsibilities: ['Analyze marketing data and performance metrics', 'Create detailed reports and dashboards', 'Identify trends and optimization opportunities', 'Optimize marketing campaigns based on data', 'Present insights to stakeholders', 'Track KPIs and ROI metrics', 'Conduct A/B testing and experiments'],
    requirements: ['Data analysis and statistical skills', 'Excel and spreadsheet proficiency', 'Analytics tools expertise (Google Analytics, Tableau)', 'Statistical knowledge', 'Business acumen and strategic thinking', 'SQL and database query skills', 'Strong communication skills'],
    benefits: ['Remote flexibility', 'Analytics tools and resources', 'Data insights access', 'Learning programs', 'Career advancement', 'Flexible schedule', 'Performance bonuses'],
    aboutCompany: 'Data Insights provides marketing analytics solutions for businesses.',
    postedDate: '2025-09-28',
    applicants: 31,
    views: 687
  },
];
