export const marketingJobs = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0',
    tags: ['SEO', 'Content', 'Analytics'],
    title: 'Digital Marketing Specialist',
    company: 'Creative Agency',
    location: 'Phnom Penh',
    description:
      'Manage SEO campaigns, content strategies, and web analytics to optimize digital presence and engagement.',
    salary: '$800 - $1,200 / month',
    experience: '2+ years',
    jobType: 'Full-time',
    benefits: ['Health insurance', 'Flexible hours', 'Annual bonus'],
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0',
    tags: ['Social Media', 'Campaigns'],
    title: 'Social Media Manager',
    company: 'Brand Solutions',
    location: 'Remote',
    description:
      'Develop and execute social media strategies, analyze engagement metrics, and manage content calendars.',
    salary: '$900 - $1,500 / month',
    experience: '3+ years',
    jobType: 'Remote',
    benefits: ['Work from home', 'Training budget', 'Paid vacations'],
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7',
    tags: ['Copywriting', 'Strategy'],
    title: 'Content Marketing Manager',
    company: 'Media Group',
    location: 'Phnom Penh',
    description:
      'Lead content creation, editorial planning, and marketing campaigns to enhance brand presence.',
    salary: '$1,000 - $1,500 / month',
    experience: '4+ years',
    jobType: 'Full-time',
    benefits: ['Health insurance', 'Team retreats', 'Professional development'],
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
    tags: ['Google Ads', 'PPC', 'ROI'],
    title: 'Performance Marketing Specialist',
    company: 'Growth Marketing',
    location: 'Siem Reap',
    description:
      'Plan and optimize PPC campaigns, track ROI, and analyze performance data to improve conversions.',
    salary: '$900 - $1,400 / month',
    experience: '2+ years',
    jobType: 'Full-time',
    benefits: ['Health coverage', 'Bonuses', 'Flexible schedule'],
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    tags: ['Brand Strategy', 'Marketing'],
    title: 'Brand Marketing Manager',
    company: 'Retail Corp',
    location: 'Phnom Penh',
    description:
      'Develop brand strategies, coordinate campaigns, and work with cross-functional teams to drive brand growth.',
    salary: '$1,200 - $1,800 / month',
    experience: '5+ years',
    jobType: 'Full-time',
    benefits: ['Health insurance', 'Team outings', 'Year-end bonus'],
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312',
    tags: ['Email Marketing', 'Automation'],
    title: 'Email Marketing Specialist',
    company: 'E-commerce Hub',
    location: 'Remote',
    description:
      'Design and execute email campaigns, automate workflows, and analyze email performance metrics.',
    salary: '$800 - $1,300 / month',
    experience: '2+ years',
    jobType: 'Remote',
    benefits: ['Flexible hours', 'Remote work', 'Skill development allowance'],
  },
];
